### ISSUE TITLE
legal problems

### ISSUE THREAD

**Issue by chegewara** [martinberlin/cale-idf#84]
This point in readme is illegal:
https://github.com/martinberlin/cale-idf#fork-policy

It is illegal, because of this part of licence:
```
4. Redistribution. **You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications,** and in Source or Object form, provided that You
      meet the following conditions:
```

**Comment by martinberlin** [comment]
Hello @chegewara 
I don't have anything against "copying" or redistributing this in fact is cloned more than 30 times a month so there should be a lot of copies in the users of the component personal computers. 
What I don't like as owner of this repository is to have forks without any reason because often face myself to look into forks of other libraries, searching to see if someone added a feature before adding it myself, just to look at hundreds of mostly old copies of a forked component.

So it's an advice not do it but nothing else. Thanks for pointing it out, I will re-phrase it some better manner in the next days, but I'm not planning to take this note completely out since I dislike having hundreds of forks just because many people use forking to bookmark stuff without collaborating in a single line of the code.
