### ISSUE TITLE
Partial refresh failure on GDEY075T7

### ISSUE THREAD

**Issue by shREYas-310** [martinberlin/cale-idf#97]
**Describe the bug**
The partial refresh is not working as expected on the GDEY075T7 model. Values get updated on the e-paper display but, the previous values remains on the display which leads to overlapping of the values on that particular partial window of the e-paper display.

**Specify what Model/Classname of epaper you are using.**
Display model used is GDEY075T7

1. If it’s a rendering issue please upload photos of how it renders on your display
![Untitled](https://github.com/martinberlin/cale-idf/assets/114473594/db2755ac-df9a-454a-aff3-f4c53bba6dda)

**Expected behavior**
Partial update should happen in such a way that the previous value on the e-paper display should get updated to a recent value instead of overlapping on the previous value

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10
 - Browser [e.g. chrome, safari] - Brave
 - Version [e.g. 22] - v1.60.118

**Comment by martinberlin** [comment]
Sadly I don't have anymore one of such displays at hand @XAG-labs . What you can try is to send first the whole area to white, execute the partial commands and then try again with the partial buffer.
If that works you can make a Pull request and contribute to this project. Another alternative is to check how is done in GxEPD /(Or GxEPD2) and replicate those commands in the class. 
Partial updates in SPI displays is always hard to get working 100% correctly and I really stopped trying since I don't have the time anymore to have this battles when I have many other important matters to resolve

**Comment by XAG-labs** [comment]
> Sadly I don't have anymore one of such displays at hand @XAG-labs . What you can try is to send first the whole area to white, execute the partial commands and then try again with the partial buffer. If that works you can make a Pull request and contribute to this project. Another alternative is to check how is done in GxEPD /(Or GxEPD2) and replicate those commands in the class. Partial updates in SPI displays is always hard to get working 100% correctly and I really stopped trying since I don't have the time anymore to have this battles when I have many other important matters to resolve

Thank you Mr. Martin for the reply. 
I will definitely try both the solutions that you have provided and I will update you regarding them

**Comment by martinberlin** [comment]
Hello @XAG-labs 
Could you advance trying some way to fix this partial refresh issue?
Just tell if I can help you at some point.

**Comment by XAG-labs** [comment]
> Hello @XAG-labs Could you advance trying some way to fix this partial refresh issue? Just tell if I can help you at some point.

Hello Mr. Martin,
The first solution which you have provided which is, "send first the whole area to white, execute the partial commands and then try again with the partial buffer." did not work unfortunately.
The second solution should work because the partial refresh is working absolutely fine in Arduino using the GxEPD2 library. 
Right now as I'm busy with other work, I couldn't start with the second solution. 
I will definitely contact you if I need any help.

Thank you,
Shreyas

**Comment by martinberlin** [comment]
Closing here since it's 3 months of inactivity. @shREYas-310 please open another issue about it if there is really an interest to help solving it
